# Generated by Django 4.2.7 on 2024-03-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.CharField(max_length=150)),
                ('verse_content', models.TextField()),
                ('motivation', models.TextField()),
                ('payer', models.TextField()),
            ],
        ),
    ]
