# Generated by Django 4.2.7 on 2024-03-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_word_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='payer',
            new_name='prayer',
        ),
    ]
