# Generated by Django 4.2.11 on 2024-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_visits_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateField(blank=True, null=tuple, unique=True),
            preserve_default=tuple,
        ),
    ]
