# Generated by Django 4.2.11 on 2024-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
